
action_selector: "soft_policies"
mask_before_softmax: True

runner: "parallel"

buffer_size: 10
batch_size_run: 10
batch_size: 10

target_update_interval_or_tau: 0.01

lr: 0.0005

obs_agent_id: False
obs_last_action: False
obs_individual_obs: False

mac: "non_shared_mac"
agent: "rnn_ns"

agent_output_type: "pi_logits"
learner: "pac_cvar_learner" # CUSTOM LEARNER
use_rnn: False
standardise_rewards: False
q_nstep: 10

critic_type: "pac_dcg_critic_ns"
state_value_type: "cv_critic_ns"

initial_entropy_coef: 30.0
final_entropy_coef: 0.01
entropy_end_ratio: 0.8

# Specify the CG
cg_edges: 'full'
cg_utilities_hidden_dim:
cg_payoffs_hidden_dim:
cg_payoff_rank:
duelling: False
msg_anytime: True
msg_iterations: 8
msg_normalized: True


name: "pac_cvar_ns"

t_max: 500500

# CVaR PARAMS
cvar_alpha: 0.1
critic_type: 'pac_critic_ns'
